services:
  # PHP Web Service
  - type: web
    name: nexaauth-app
    runtime: php
    plan: free
    buildCommand: ""
    startCommand: php -S 0.0.0.0:$PORT
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: nexaauth-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: nexaauth-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: nexaauth-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: nexaauth-db
          property: password

  # MySQL Database
  - type: pserv
    name: nexaauth-db
    runtime: mysql
    plan: free
    databases:
      - name: user_management
