services:
  # PHP Web Service (Docker)
  - type: web
    name: nexaauth-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: nexaauth-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: nexaauth-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: nexaauth-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: nexaauth-db
          property: password

  # MySQL Database
  - type: pserv
    name: nexaauth-db
    runtime: mysql
    plan: free
    databases:
      - name: user_management
